syntax = "proto3";

option go_package = "mosaic-client.com/gen/face_detection";

package proto.face_detection;

// Face detection processing service definition
service FaceDetectionService {
    // Send face bytes for potential visitors, get back briefing if known or unknown signal
    rpc ProcessVisitorFaces (ProcessVisitorFacesRequest) returns (ProcessVisitorFacesResponse) {}
    
    // Used to register a new face when a new face is detected while app is recording
    rpc RegisterVisitorFace (RegisterVisitorFaceRequest) returns (RegisterVisitorFaceResponse) {}

    // Send face bytes for loading user profile, get back profile_id if known or request to create new profile
    rpc SyncProfile (SyncProfileRequest) returns (SyncProfileResponse) {}
}

// The request containing the face image in bytes and profile_id
message ProcessVisitorFacesRequest {
    bytes face_bytes = 1;
    string session_token = 2;
}

// single face message containing the metadata and if we should register name for it
message FaceResult {                                                                                                                  
    bool is_known = 1;
    string name = 2;                                                                                                                
    string briefing = 3;                                                                                                              
    repeated float face_embedding = 4; // 128 dim embedding
    int32 visitor_id = 5;
}  

// The response containing briefing if face matches an existing face
// or is_known false if face doesnt match
message ProcessVisitorFacesResponse {
    bool face_detected = 1; // used so if no face is detected it doesnt send a req
    repeated FaceResult faces = 2;
    bool success = 3; // boolean to see if the process succeeded for handling retry
    bool non_visitor_face = 4; // boolean to return true if the face sent is the current profile's face
}

// Response containing data to register a new unknown visitor face
message RegisterVisitorFaceRequest {
    repeated float face_embedding = 1; // 128 dim embedding
    string session_token = 2;
    string visitor_name = 3;
}

// Response containing data about if request succeeded and visitor id
message RegisterVisitorFaceResponse {
    bool success = 1;
    int32 visitor_id = 2;
}

// The request containing the array of face image in bytes
message SyncProfileRequest {
    repeated bytes face_bytes = 1;
}

// contains one face embedding
message FaceEmbedding {
    repeated float face_embedding = 1; // 128 dim emb
}

// response for the sync profile
message SyncProfileResponse {
    bool face_detected = 1; // used so can prompt the frontend to maybe get a clearer view?
    bool success = 2; // used for retry logic
    string session_token = 3;
    repeated FaceEmbedding face_embedding = 4;
}