services:
  valkey:
    image: valkey/valkey:8-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkeydata:/data

  db:
    image: pgvector/pgvector:pg17
    restart: always
    shm_size: 128mb # Set shared memory limit
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: pg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
  valkeydata: